/**
 * Config-regression CI — the playbook's "continuous evals in CI" play.
 *
 * The configuration that steers a fleet (the spec, the compiled agents and
 * skills, the hooks, the shared knowledge) deserves the regression testing
 * code gets, and it should run on any change to that configuration rather
 * than on a human remembering to. fleetsmith already has the deterministic
 * suite — `qa` (spec gate, per-target compile, handoff graph, capability
 * leaks, loop bounds, drift) and `eval --stage 2` (trigger discrimination plus
 * the held-out fleet corpus) — and both run with no model available, so the
 * workflow needs no API key and costs nothing but CI minutes.
 *
 * Opt-in via `fleet.ci: github`, because writing a workflow file into a
 * project that may not use GitHub is presumptuous. Target-independent, so
 * every adapter emits the identical file and `buildAll` deduplicates it.
 */

export const CI_WORKFLOW_PATH = '.github/workflows/fleet-qa.yml';

export function ciWorkflow(spec, { specPath = 'fleet.yaml' } = {}) {
  const watched = [
    specPath,
    '.claude/**',
    '.opencode/**',
    '.goose/**',
    `${spec.fleet.shared}/**`,
    'CLAUDE.md',
    'AGENTS.md',
    'opencode.json',
  ];
  return `# Generated by fleetsmith for the ${spec.fleet.name} fleet (fleet.ci: github).
#
# Regression-tests the harness configuration the way code is tested: on every
# change to the spec, the compiled agents/skills/hooks, or the shared fleet
# knowledge. Both commands are deterministic and need no model or API key.
#
#   qa   — spec gate, per-target compile, handoff graph, capability leaks,
#          loop bounds, and drift between ${specPath} and what is committed
#   eval — skill trigger discrimination + the held-out fleet corpus
#
# A red run means the harness would behave differently from its spec, or a
# skill would stop firing on the prompts it was written for. Fix the spec and
# rebuild (\`fleetsmith build ${specPath} --target all --force\`) — do not
# hand-edit generated files to make it green.
name: fleet qa

on:
  pull_request:
    paths:
${watched.map((p) => `      - '${p}'`).join('\n')}
  push:
    branches: [main]
    paths:
${watched.map((p) => `      - '${p}'`).join('\n')}

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      # npx prefers a project-local fleetsmith when one is installed; pin a
      # version here (fleetsmith@x.y.z) once the harness is stable so a newer
      # compiler cannot turn drift detection red on its own.
      - name: Spec gate, compile, handoff graph, capability leaks, drift
        run: npx --yes fleetsmith qa ${specPath} --built .
      - name: Skill trigger tests and held-out fleet corpus
        run: npx --yes fleetsmith eval ${specPath} --stage 2
`;
}
