/**
 * Protected-path guardrails — the deterministic layer behind "do not edit X".
 *
 * From the AI-native SDLC playbook (Stage 3, hooks as build-time guardrails;
 * Stage 4, "the loop itself needs protecting"): a skill or prompt is an
 * advisory control, and a policy that must always hold needs a hook behind it
 * that blocks the action and explains itself. The two paths a fleet must never
 * let its own agents touch are (1) the inputs of its objective checks — the
 * test files a fixing agent could weaken until they pass — and (2) the fleet's
 * own gate scripts, because an agent that can edit its SubagentStop gate has
 * no gate. Authors declare the first set in `fleet.guardrails.protectedPaths`;
 * the compiler adds the second unconditionally.
 *
 * Per target:
 *  - Claude Code: a `PreToolUse` hook on the file-editing tools and on Bash,
 *    running the generated `guard-paths.sh` (exit 2 = blocked, stderr = why).
 *  - opencode: each agent's `permission.edit` map denies the globs, which is
 *    enforced by the runtime rather than read by the model.
 *  - goose: has no path-level permission, so the constraint is stated in the
 *    recipe instructions — advisory, and documented as such.
 */

export const GUARD_PATH = 'scripts/guard-paths.sh';

/**
 * How far after a write-shaped token the Bash arm still counts a protected path
 * as that command's argument. Wide enough for real flag lists
 * (`rm -rf --preserve-root test/x`), narrow enough that an unrelated mention
 * later in the same command is not attributed to it.
 */
export const WRITE_GAP = 60;

/** Declared globs plus the fleet's own gate scripts. Order is stable for deterministic output. */
export function protectedPathsFor(spec) {
  const auto = `${spec.fleet.local}/scripts/**`;
  const declared = spec.fleet.guardrails?.protectedPaths ?? [];
  return [...new Set([auto, ...declared])];
}

/**
 * Translate a double-star glob into a POSIX `case` pattern. In `case`, `*`
 * already matches across slashes, so "a/<double-star>" becomes "a/*" and
 * "<double-star>/x" becomes "*x". The result is slightly broader than the glob
 * (the second form also matches "xfoo"); for a guard, over-blocking with an
 * explanation beats under-blocking.
 */
export function casePattern(glob) {
  return String(glob).replace(/\*\*\//g, '*').replace(/\*\*/g, '*');
}

/**
 * The literal prefix of a glob before its first wildcard — what a shell
 * command must mention to be suspected of writing into the protected set.
 * "test/<double-star>" → "test/", "src/gen/*.js" → "src/gen/", "*.snap" → "" (skipped).
 */
export function literalPrefix(glob) {
  const idx = String(glob).search(/[*?]/);
  const literal = idx === -1 ? String(glob) : String(glob).slice(0, idx);
  return literal.length >= 2 ? literal : '';
}

/**
 * The generated hook. POSIX sh, no dependencies beyond sed/grep. Reads the
 * PreToolUse payload on stdin; for file-editing tools it matches the target
 * path, for Bash it applies a conservative write-shaped heuristic (a protected
 * prefix appearing AFTER a redirect, in-place edit, move, copy, delete or
 * checkout token). Exit 2 blocks the call and returns the reason to the agent; the
 * verdict is recorded through the fleet's telemetry logger, which never
 * changes it.
 */
export function guardScript(spec) {
  const globs = protectedPathsFor(spec);
  const patterns = globs.map(casePattern);
  const prefixes = [...new Set(globs.map(literalPrefix).filter(Boolean))];
  const list = globs.join(', ');
  const caseArms = patterns.map((p) => `        ${p}) blocked=1 ;;`).join('\n');
  // Regex-escaped (dots) and single-quoted: the validator restricts globs to
  // [A-Za-z0-9._-/*?], so nothing else needs escaping inside ERE or sh.
  const prefixList = prefixes.map((p) => `'${p.replace(/\./g, '\\.')}'`).join(' ') || "''";

  return `#!/bin/sh
# Protected-path guard for the ${spec.fleet.name} fleet (generated by fleetsmith).
#
# Runs as a Claude Code PreToolUse hook on Edit/Write/MultiEdit/NotebookEdit and
# on Bash. Exit 2 blocks the tool call and returns stderr to the agent as the
# reason; exit 0 lets it through. Registered in .claude/settings.json.
#
# Protected: ${list}
# Patterns are shell globs against the project-relative path; "*" also crosses
# directory boundaries. The Bash check is a heuristic (a protected prefix plus a
# write-shaped token followed by a protected prefix) — OS-level sandboxing is
# what closes that gap fully.
set -u

payload=$(cat 2>/dev/null || true)
[ -n "$payload" ] || exit 0

tool=$(printf '%s' "$payload" | sed -n 's/.*"tool_name"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')
agent=$(printf '%s' "$payload" | sed -n 's/.*"agent_type"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')
[ -n "$agent" ] || agent='-'
log="$(dirname "$0")/log-event.sh"
log_event() { [ -f "$log" ] && sh "$log" "$1" "$2" "$3" >/dev/null 2>&1 || true; }
root=\${CLAUDE_PROJECT_DIR:-$(pwd)}

explain() {
    echo "Guardrail: '$1' is a protected path for the ${spec.fleet.name} fleet ($2)." >&2
    echo "Protected: ${list}" >&2
    echo "Protected paths are the inputs of this fleet's objective checks and its own gates; an agent that can edit them can pass a check without meeting it. If the task genuinely requires this change, stop and report it in your handoff as a finding for a human to make — do not work around the block." >&2
}

case "$tool" in
  Edit|Write|MultiEdit|NotebookEdit)
    # Two passes rather than sed alternation: BSD sed has no \\| in basic regex.
    target=$(printf '%s' "$payload" | sed -n 's/.*"file_path"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')
    [ -n "$target" ] || target=$(printf '%s' "$payload" | sed -n 's/.*"notebook_path"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')
    [ -n "$target" ] || exit 0
    case "$target" in
        "$root"/*) rel=\${target#"$root"/} ;;
        *) rel=$target ;;
    esac
    rel=\${rel#./}
    blocked=0
    case "$rel" in
${caseArms || '        __none__) ;;'}
    esac
    if [ "$blocked" = 1 ]; then
        explain "$rel" "$tool"
        log_event guard_block "$agent" "$tool $rel"
        exit 2
    fi
    ;;
  Bash)
    cmd=$(printf '%s' "$payload" | sed -n 's/.*"command"[[:space:]]*:[[:space:]]*"\\(.*\\)".*/\\1/p')
    [ -n "$cmd" ] || exit 0
    # Strip the redirects that only silence output, then look for a write-shaped
    # token FOLLOWED CLOSELY by a protected prefix: a redirect into it, or
    # rm/mv/cp/tee/truncate/sed -i/git checkout|restore|clean with it among the
    # arguments. Merely mentioning the path — in a grep, a cat, a commit message —
    # is not a write. POSIX ERE only.
    #
    # The gap between the token and the path is bounded (${WRITE_GAP} characters, no
    # separator or redirect inside it) because the hook payload arrives as ONE
    # line: newlines are escaped, so grep sees a heredoc's whole body as a single
    # line and an unbounded gap matches any write-ish word anywhere against any
    # protected path anywhere. That over-blocked a heredoc whose prose merely
    # mentioned a protected path, which is how this bound got here.
    stripped=$(printf '%s' "$cmd" | sed -e 's/2>&1//g' -e 's/[12]\\{0,1\\}>[[:space:]]*\\/dev\\/null//g')
    for prefix in ${prefixList}; do
        [ -n "$prefix" ] || continue
        if printf '%s' "$stripped" | grep -Eq ">>?[[:space:]]*[\\"']?$prefix|(^|[^[:alnum:]_])(tee|rm|mv|cp|truncate|sed[[:space:]]+-[a-zA-Z]*i[^[:space:]]*|git[[:space:]]+(checkout|restore|clean))[^|;&<>\\\`]{0,${WRITE_GAP}}$prefix"; then
            explain "$prefix" "Bash writes into a protected prefix"
            echo "If this command only reads the protected path, it should not redirect into it or pass it to a command that writes; redirect elsewhere or use the Read tool instead." >&2
            log_event guard_block "$agent" "Bash write into protected path $prefix"
            exit 2
        fi
    done
    ;;
esac
exit 0
`;
}

/**
 * Prose for agent prompts: what is protected and what to do when a task seems
 * to need it. The hook enforces this on Claude Code and the permission map on
 * opencode; on goose this paragraph is the whole control.
 */
export function guardrailsBlock(spec, { enforced = true } = {}) {
  const globs = protectedPathsFor(spec);
  const lines = ['## Guardrails', ''];
  lines.push(
    `These paths are protected — never edit, overwrite, move or delete anything under them: ${globs.map((g) => `\`${g}\``).join(', ')}.`
  );
  lines.push(
    enforced
      ? 'A hook blocks such edits and records the attempt. If your task appears to need one, that is a finding, not an obstacle: stop, state exactly which change a human would have to make and why, and continue with what you can do.'
      : 'Nothing enforces this on this target, so the rule is yours to keep. If your task appears to need such a change, that is a finding, not an obstacle: stop, state exactly which change a human would have to make and why, and continue with what you can do.'
  );
  lines.push(
    'The point is the checks: an agent that can edit a test, a fixture, or its own gate can satisfy the check without meeting the requirement, and the evidence of that disappears with the edit.'
  );
  return lines.join('\n');
}
