/**
 * Run telemetry — the OBSERVE stage of the evolution loop.
 *
 * A fleet run produces plenty of signal and, until now, discarded all of it.
 * The handover gate in particular already decides, per agent per stop, whether
 * a handoff was complete — then throws that verdict away on exit. This module
 * emits a dependency-free logger the gate and the orchestrator call, appending
 * one JSON object per line to <workspace>/runs/<run_id>/events.jsonl.
 *
 * Design constraints:
 *  - **Free.** Everything recorded here is a byproduct of work already
 *    happening. The OBSERVE stage never makes an LLM call.
 *  - **File-based.** JSONL in the workspace: greppable, diffable, no service
 *    dependency, and it works identically on all three targets.
 *  - **Borrowed vocabulary, not a dependency.** Event and field names follow
 *    OpenTelemetry's GenAI semantic conventions (`invoke_agent`,
 *    `execute_tool`, `gen_ai.evaluation.result`) so a future exporter is a
 *    field mapping rather than a rewrite. The conventions themselves were
 *    still unstable as of 2026-07 — they were removed outright from the main
 *    semantic-conventions repo in v1.43.0 — so taking the dependency now would
 *    buy churn, not stability.
 *  - **Never in a prompt.** Run state stays in files. Injecting a run id or
 *    counter into an agent body would break the cache-stability invariant in
 *    compile/agent-prompt.js.
 */

export const TELEMETRY_PATH = 'scripts/log-event.sh';

/** Events the logger understands. Keep in sync with the orchestrator prose. */
export const EVENTS = [
  'run_start',
  'phase_start',
  'invoke_agent',
  'gate_pass',
  'gate_block',
  'execute_tool_error',
  'feedback',
  'evaluation',
  'run_end',
];

/**
 * The logger script. POSIX sh, no dependencies beyond date/sed/tr, because it
 * runs wherever the harness is checked out and is called from a hook that must
 * not fail the build if the environment is spartan.
 *
 * Usage: sh log-event.sh <event> [agent] [detail]
 *
 * It is deliberately fail-soft: telemetry must never block a run or change a
 * gate verdict. Every failure path exits 0.
 */
export function logEventScript(spec) {
  const runsDir = `${spec.fleet.workspace}/runs`;
  return `#!/bin/sh
# Run telemetry for the ${spec.fleet.name} fleet (generated by fleetsmith).
#
# Usage: sh ${runsDir}/../${TELEMETRY_PATH} <event> [agent] [detail]
#
# Appends one JSON line to ${runsDir}/<run_id>/events.jsonl. Event names follow
# OpenTelemetry GenAI conventions so these records can be exported later.
#
# Fail-soft by contract: telemetry never blocks a run. Every path exits 0.
set -u

event=\${1:-}
agent=\${2:-}
detail=\${3:-}
[ -n "$event" ] || exit 0

runs_dir=$(dirname "$0")/../runs
mkdir -p "$runs_dir" 2>/dev/null || exit 0
current="$runs_dir/CURRENT"

# run_start mints the id; every other event joins the run in progress. A run
# that was never opened (someone invoked an agent directly) still gets a home
# rather than losing its events.
if [ "$event" = "run_start" ] || [ ! -f "$current" ]; then
    run_id=$(date -u +%Y%m%dT%H%M%SZ 2>/dev/null || echo unknown)
    printf '%s' "$run_id" > "$current" 2>/dev/null || exit 0
fi
run_id=$(cat "$current" 2>/dev/null) || exit 0
[ -n "$run_id" ] || exit 0

out_dir="$runs_dir/$run_id"
mkdir -p "$out_dir" 2>/dev/null || exit 0

# Flatten and escape for JSON: backslash, quote, tab, then newlines to spaces.
esc() {
    printf '%s' "\${1:-}" | sed -e 's/\\\\/\\\\\\\\/g' -e 's/"/\\\\"/g' -e 's/	/ /g' | tr '\\n' ' '
}

ts=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo unknown)
printf '{"ts":"%s","run_id":"%s","event":"%s","agent":"%s","detail":"%s"}\\n' \\
    "$ts" "$(esc "$run_id")" "$(esc "$event")" "$(esc "$agent")" "$(esc "$detail")" \\
    >> "$out_dir/events.jsonl" 2>/dev/null || exit 0

# run_end closes the run so the next run_start opens a fresh id.
[ "$event" = "run_end" ] && rm -f "$current" 2>/dev/null

exit 0
`;
}

/**
 * The orchestrator's telemetry instructions. Static text only — no run ids,
 * dates, or counters, so agent and skill bodies stay cache-stable.
 *
 * Kept to one copy-pasteable command per point: on opencode and goose this is
 * prose the model has to choose to follow, and terseness is what makes that
 * actually happen.
 */
export function telemetryBlock(spec) {
  const script = `${spec.fleet.workspace}/${TELEMETRY_PATH}`;
  return [
    '## Run telemetry',
    '',
    `Record what happened so the harness can be improved from evidence rather than memory. Each command appends one line to \`${spec.fleet.workspace}/runs/<run_id>/events.jsonl\` and never fails the run.`,
    '',
    `- At the start of Phase 0: \`sh ${script} run_start\``,
    `- At the start of each phase: \`sh ${script} phase_start "" "<phase name>"\``,
    `- Before delegating to an agent: \`sh ${script} invoke_agent <agent>\``,
    `- When a tool or command fails and you retry: \`sh ${script} execute_tool_error <agent> "<what failed>"\``,
    `- At Completion: \`sh ${script} run_end "" "<done|partial|blocked>"\``,
    '',
    'Never edit past event lines — the file is append-only, and a rewritten history is worse than none.',
  ].join('\n');
}
